
server:
  port: 8000

spring:
    datasource:
        name: tyxkxt
        url: jdbc:mysql://127.0.0.1:3306/tyxkxt
        username: tyxkxt
        password: tyxkxt
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    devtools:
        restart:
          enabled: true  #设置开启热部署
          additional-paths: src/main/java #重启目录
          exclude: WEB-INF/**



pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

##httpclient
#http:
##最大连接数
#  maxTotal : 100
##并发数
#  defaultMaxPerRoute : 20
##创建连接的最长时间
#  connectTimeout: 1000
##从连接池中获取到连接的最长时间
#  connectionRequestTimeout: 500
##数据传输的最长时间
#  socketTimeout: 10000
##提交请求前测试连接是否可用
#  staleConnectionCheckEnabled: true
